
development:
  adapter: mysql
  database: library_development
  username: group
  password: music
  host: localhost
test:
  adapter: mysql
  database: library_test
  username: group
  password: music
  host: localhost
production:
  adapter: mysql
  database: library_production
  username: group
  password: music
  host: localhost
